# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from functions.dataLoad import dataLoad

class Ui_MainWindow(object):

    #Run this when class is run
    def __init__(self):
        self.setupUi(MainWindow) #set UI

        #Adding functionality to program
        #Dataload
        self.dataload_btn.clicked.connect(self.dataloadUI) #On click, run dataloadUI function

    #Load data
    def dataloadUI(self):
        filename = self.dataload_input.text()
        #Get correct filename
        try:
            data,msg = dataLoad(filename)
            self.print_(msg)
            #Print message
            msg_success = ("Data loaded succesfully from {}\n").format(filename)
            self.print_(msg_success)

        except FileNotFoundError:
            self.print_("File not found, please try again\n")

    #print text into display_window
    def print_(self,text):
        self.display_window.insertPlainText(text)
        self.display_window.ensureCursorVisible() #Stay at bottom of window

    ####################
    #Everything below this point has been generated by Qt Designer
    #However some parts have been modified.
    ####################

    #The lines should be easy to read, such as:
    #self.dataload_box.setObjectName("dataload_box")
    #Sets the objectname of a groupbox to dataload_box
    def setupUi(self, MainWindow):
        #Initalization of main window
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(868, 586)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        #Welcome label and header of program, separated with line
        self.welcome_label = QtWidgets.QLabel(self.centralwidget)
        self.welcome_label.setObjectName("welcome_label")
        self.verticalLayout.addWidget(self.welcome_label, 0, QtCore.Qt.AlignHCenter)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        #Frame for content of program
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMaximumSize(QtCore.QSize(1000000, 300))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        #Frame containing the dataload and commands
        self.command_frame = QtWidgets.QFrame(self.frame)
        self.command_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.command_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.command_frame.setObjectName("command_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.command_frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.dataload_box = QtWidgets.QGroupBox(self.command_frame)
        self.dataload_box.setObjectName("dataload_box")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.dataload_box)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.dataload_label = QtWidgets.QLabel(self.dataload_box)
        self.dataload_label.setObjectName("dataload_label")
        self.horizontalLayout_2.addWidget(self.dataload_label)
        #Dataload box
        self.dataload_input = QtWidgets.QLineEdit(self.dataload_box)
        self.dataload_input.setMinimumSize(QtCore.QSize(104, 21))
        self.dataload_input.setText("")
        self.dataload_input.setObjectName("dataload_input")
        self.horizontalLayout_2.addWidget(self.dataload_input)
        #The dataload button
        self.dataload_btn = QtWidgets.QPushButton(self.dataload_box)
        self.dataload_btn.setObjectName("dataload_btn")
        #Layout and lines
        self.horizontalLayout_2.addWidget(self.dataload_btn)
        self.verticalLayout_3.addWidget(self.dataload_box)
        self.line_5 = QtWidgets.QFrame(self.command_frame)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_3.addWidget(self.line_5)
        #command_box
        self.command_box = QtWidgets.QGroupBox(self.command_frame)
        self.command_box.setObjectName("command_box")
        self.gridLayout = QtWidgets.QGridLayout(self.command_box)
        self.gridLayout.setObjectName("gridLayout")
        #Statistics button
        self.stat_btn = QtWidgets.QPushButton(self.command_box)
        self.stat_btn.setObjectName("stat_btn")
        self.gridLayout.addWidget(self.stat_btn, 0, 0, 1, 1)
        #show data button
        self.showdata_btn = QtWidgets.QPushButton(self.command_box)
        self.showdata_btn.setObjectName("showdata_btn")
        self.gridLayout.addWidget(self.showdata_btn, 0, 2, 1, 1)
        #plot button
        self.plot_btn = QtWidgets.QPushButton(self.command_box)
        self.plot_btn.setObjectName("plot_btn")
        self.gridLayout.addWidget(self.plot_btn, 0, 1, 1, 1)
        #Layouts and lines
        self.verticalLayout_3.addWidget(self.command_box)
        self.horizontalLayout.addWidget(self.command_frame)
        self.line_3 = QtWidgets.QFrame(self.frame)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout.addWidget(self.line_3)
        #Filter box
        self.filterdata_box = QtWidgets.QGroupBox(self.frame)
        self.filterdata_box.setMaximumSize(QtCore.QSize(350, 340))
        self.filterdata_box.setObjectName("filterdata_box")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.filterdata_box)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.bacteria_box = QtWidgets.QGroupBox(self.filterdata_box)
        #Bacteria box
        self.bacteria_box.setObjectName("bacteria_box")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.bacteria_box)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        #Set check boxes for bacteria filters and mark them as checked
        self.bac1_chk = QtWidgets.QCheckBox(self.bacteria_box)
        self.bac1_chk.setChecked(True)
        self.bac1_chk.setObjectName("bac1_chk")
        self.verticalLayout_2.addWidget(self.bac1_chk)
        self.bac2_chk = QtWidgets.QCheckBox(self.bacteria_box)
        self.bac2_chk.setChecked(True)
        self.bac2_chk.setObjectName("bac2_chk")
        self.verticalLayout_2.addWidget(self.bac2_chk)
        self.bac3_chk = QtWidgets.QCheckBox(self.bacteria_box)
        self.bac3_chk.setChecked(True)
        self.bac3_chk.setObjectName("bac3_chk")
        self.verticalLayout_2.addWidget(self.bac3_chk)
        self.bac4_chk = QtWidgets.QCheckBox(self.bacteria_box)
        self.bac4_chk.setChecked(True)
        self.bac4_chk.setObjectName("bac4_chk")
        self.verticalLayout_2.addWidget(self.bac4_chk)
        self.horizontalLayout_4.addWidget(self.bacteria_box)
        #Range filters
        self.range_box = QtWidgets.QGroupBox(self.filterdata_box)
        self.range_box.setMaximumSize(QtCore.QSize(166, 242))
        self.range_box.setObjectName("range_box")
        self.formLayout = QtWidgets.QFormLayout(self.range_box)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setObjectName("formLayout")
        #The filtering boxes with inputs and buttons
        #Growth rate
        self.growth_label = QtWidgets.QLabel(self.range_box)
        self.growth_label.setObjectName("growth_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.growth_label)
        self.growthto_label = QtWidgets.QLabel(self.range_box)
        self.growthto_label.setObjectName("growthto_label")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.growthto_label)
        self.growthto_input = QtWidgets.QLineEdit(self.range_box)
        self.growthto_input.setMinimumSize(QtCore.QSize(70, 21))
        self.growthto_input.setMaximumSize(QtCore.QSize(70, 21))
        self.growthto_input.setObjectName("growthto_input")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.growthto_input)
        self.growth_btn = QtWidgets.QPushButton(self.range_box)
        self.growth_btn.setObjectName("growth_btn")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.SpanningRole, self.growth_btn)
        self.line_4 = QtWidgets.QFrame(self.range_box)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.line_4)
        #Temperature
        self.temp_label = QtWidgets.QLabel(self.range_box)
        self.temp_label.setObjectName("temp_label")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.temp_label)
        self.tempfrom_label = QtWidgets.QLabel(self.range_box)
        self.tempfrom_label.setObjectName("tempfrom_label")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.tempfrom_label)
        self.tempto_label = QtWidgets.QLabel(self.range_box)
        self.tempto_label.setObjectName("tempto_label")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.tempto_label)
        self.tempfrom_input = QtWidgets.QLineEdit(self.range_box)
        self.tempfrom_input.setMinimumSize(QtCore.QSize(70, 21))
        self.tempfrom_input.setMaximumSize(QtCore.QSize(70, 21))
        self.tempfrom_input.setObjectName("tempfrom_input")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.tempfrom_input)
        self.tempBtn = QtWidgets.QPushButton(self.range_box)
        self.tempBtn.setObjectName("tempBtn")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.SpanningRole, self.tempBtn)
        #Labels for the filters
        self.growthfrom_label = QtWidgets.QLabel(self.range_box)
        self.growthfrom_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.growthfrom_label.setObjectName("growthfrom_label")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.growthfrom_label)
        self.growthfrom_input = QtWidgets.QLineEdit(self.range_box)
        self.growthfrom_input.setMinimumSize(QtCore.QSize(70, 21))
        self.growthfrom_input.setMaximumSize(QtCore.QSize(70, 21))
        self.growthfrom_input.setClearButtonEnabled(False)
        self.growthfrom_input.setObjectName("growthfrom_input")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.growthfrom_input)
        self.tempto_input = QtWidgets.QLineEdit(self.range_box)
        self.tempto_input.setMinimumSize(QtCore.QSize(70, 21))
        self.tempto_input.setMaximumSize(QtCore.QSize(70, 21))
        self.tempto_input.setText("")
        self.tempto_input.setObjectName("tempto_input")
        #Layouts and lines
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.tempto_input)
        self.horizontalLayout_4.addWidget(self.range_box)
        self.horizontalLayout.addWidget(self.filterdata_box)
        self.verticalLayout.addWidget(self.frame)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        #Display window
        self.display_box = QtWidgets.QGroupBox(self.centralwidget)
        self.display_box.setObjectName("display_box")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.display_box)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.display_window = QtWidgets.QPlainTextEdit(self.display_box)
        self.display_window.setReadOnly(True)
        self.display_window.setObjectName("display_window")
        self.horizontalLayout_5.addWidget(self.display_window)
        self.line_6 = QtWidgets.QFrame(self.display_box)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout_5.addWidget(self.line_6)
        #Filtering window
        self.filter_window = QtWidgets.QPlainTextEdit(self.display_box)
        self.filter_window.setMaximumSize(QtCore.QSize(200, 1000000))
        self.filter_window.setAcceptDrops(False)
        self.filter_window.setAutoFillBackground(False)
        self.filter_window.setReadOnly(True)
        self.filter_window.setObjectName("filter_window")
        self.horizontalLayout_5.addWidget(self.filter_window)
        self.verticalLayout.addWidget(self.display_box)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 868, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        #Run retranslateUI function
        self.retranslateUi(MainWindow)

    #This function sets the displaynames, placeholdertexts, tooltips and so on
    #This is the front-end of the program
    #Keep in mind the setToolTip function takes an html-syntaxed input
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Bacteria Data Analysis"))
        self.welcome_label.setText(_translate("MainWindow", "Welcome to the Bacteria Data Analysis program"))
        self.dataload_box.setTitle(_translate("MainWindow", "Dataload"))
        self.dataload_label.setText(_translate("MainWindow", "Enter the name of the datafile:"))
        self.dataload_input.setToolTip(_translate("MainWindow", "<html><head/><body><p>Please enter a filename</p></body></html>"))
        self.dataload_input.setStatusTip(_translate("MainWindow", "Enter the name of the datafile"))
        self.dataload_input.setPlaceholderText(_translate("MainWindow", "Ex: test.txt"))
        self.dataload_btn.setToolTip(_translate("MainWindow", "<html><head/><body><p>Loads the datafile given to the left</p></body></html>"))
        self.dataload_btn.setStatusTip(_translate("MainWindow", "Click to load data from filename"))
        self.dataload_btn.setText(_translate("MainWindow", "Load Data"))
        self.command_box.setTitle(_translate("MainWindow", "Commands"))
        self.stat_btn.setToolTip(_translate("MainWindow", "<html><head/><body><p>Displays statistics based on current data</p></body></html>"))
        self.stat_btn.setStatusTip(_translate("MainWindow", "Click to display statistics of current data"))
        self.stat_btn.setText(_translate("MainWindow", "Display Statistics"))
        self.showdata_btn.setToolTip(_translate("MainWindow", "<html><head/><body><p>Shows current data</p></body></html>"))
        self.showdata_btn.setStatusTip(_translate("MainWindow", "Click to show current data"))
        self.showdata_btn.setText(_translate("MainWindow", "Show data"))
        self.plot_btn.setToolTip(_translate("MainWindow", "<html><head/><body><p>Generates plots on current data</p></body></html>"))
        self.plot_btn.setStatusTip(_translate("MainWindow", "Click to generate plots of current data"))
        self.plot_btn.setText(_translate("MainWindow", "Generate plots"))
        self.filterdata_box.setTitle(_translate("MainWindow", "Filter Data"))
        self.bacteria_box.setTitle(_translate("MainWindow", "Bacteria"))
        self.bac1_chk.setToolTip(_translate("MainWindow", "<html><head/><body><p>Press to activate or deactive filter</p></body></html>"))
        self.bac1_chk.setStatusTip(_translate("MainWindow", "Click to add/remove filter"))
        self.bac1_chk.setText(_translate("MainWindow", "Salmonella enterica"))
        self.bac2_chk.setToolTip(_translate("MainWindow", "<html><head/><body><p>Press to activate or deactive filter</p></body></html>"))
        self.bac2_chk.setStatusTip(_translate("MainWindow", "Click to add/remove filter"))
        self.bac2_chk.setText(_translate("MainWindow", "Bacillus cereus"))
        self.bac3_chk.setToolTip(_translate("MainWindow", "<html><head/><body><p>Press to activate or deactive filter</p></body></html>"))
        self.bac3_chk.setStatusTip(_translate("MainWindow", "Click to add/remove filter"))
        self.bac3_chk.setText(_translate("MainWindow", "Listeria"))
        self.bac4_chk.setToolTip(_translate("MainWindow", "<html><head/><body><p>Press to activate or deactive filter</p></body></html>"))
        self.bac4_chk.setStatusTip(_translate("MainWindow", "Click to add/remove filter"))
        self.bac4_chk.setText(_translate("MainWindow", "Brochothrix thermosphacta"))
        self.range_box.setTitle(_translate("MainWindow", "Range"))
        self.growth_label.setToolTip(_translate("MainWindow", "<html><head/><body><p>Filter for growth rate</p></body></html>"))
        self.growth_label.setText(_translate("MainWindow", "Growth rate"))
        self.growthto_label.setText(_translate("MainWindow", "Upper limit"))
        self.growthto_input.setToolTip(_translate("MainWindow", "<html><head/><body><p>Enter upper limit</p></body></html>"))
        self.growthto_input.setStatusTip(_translate("MainWindow", "Enter an upper limit for the range"))
        self.growthto_input.setPlaceholderText(_translate("MainWindow", "Ex: 0.09"))
        self.growth_btn.setToolTip(_translate("MainWindow", "<html><head/><body><p>Press to add filter with limits stated above</p></body></html>"))
        self.growth_btn.setStatusTip(_translate("MainWindow", "Press button to add growth rate filter"))
        self.growth_btn.setText(_translate("MainWindow", "Add growth rate filter"))
        self.temp_label.setToolTip(_translate("MainWindow", "<html><head/><body><p>Filter for temperature</p></body></html>"))
        self.temp_label.setText(_translate("MainWindow", "Temperature"))
        self.tempfrom_label.setText(_translate("MainWindow", "Lower limit"))
        self.tempto_label.setText(_translate("MainWindow", "Upper limit"))
        self.tempfrom_input.setToolTip(_translate("MainWindow", "<html><head/><body><p>Enter lower limit</p></body></html>"))
        self.tempfrom_input.setStatusTip(_translate("MainWindow", "Enter a lower limit for the range"))
        self.tempfrom_input.setPlaceholderText(_translate("MainWindow", "Ex: 25"))
        self.tempBtn.setToolTip(_translate("MainWindow", "<html><head/><body><p>Press to add filter with limits stated above</p></body></html>"))
        self.tempBtn.setStatusTip(_translate("MainWindow", "Press button to add temperature filter"))
        self.tempBtn.setText(_translate("MainWindow", "Add temperature filter"))
        self.growthfrom_label.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Goat</p></body></html>"))
        self.growthfrom_label.setText(_translate("MainWindow", "Lower limit"))
        self.growthfrom_input.setToolTip(_translate("MainWindow", "<html><head/><body><p>Enter lower limit</p></body></html>"))
        self.growthfrom_input.setStatusTip(_translate("MainWindow", "Enter a lower limit for the range"))
        self.growthfrom_input.setPlaceholderText(_translate("MainWindow", "Ex: 0.02"))
        self.tempto_input.setToolTip(_translate("MainWindow", "<html><head/><body><p>Enter upper limit</p></body></html>"))
        self.tempto_input.setStatusTip(_translate("MainWindow", "Enter an upper limit for the range"))
        self.tempto_input.setPlaceholderText(_translate("MainWindow", "Ex: 45"))
        self.display_box.setTitle(_translate("MainWindow", "Display Window"))
        self.display_window.setToolTip(_translate("MainWindow", "<html><head/><body><p>Any information will be printed here</p></body></html>"))
        self.display_window.setStatusTip(_translate("MainWindow", "Shows any printed information"))
        self.display_window.setPlaceholderText(_translate("MainWindow", "No information printed"))
        self.filter_window.setToolTip(_translate("MainWindow", "<html><head/><body><p>This shows the active filters</p></body></html>"))
        self.filter_window.setStatusTip(_translate("MainWindow", "Shows current filters"))
        self.filter_window.setPlaceholderText(_translate("MainWindow", "No currently active filters"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv) #Syntax for pyqt
    MainWindow = QtWidgets.QMainWindow() #Define the mainwindow
    ui = Ui_MainWindow() #Call the class which runs the __init__
    MainWindow.show() #Show the program
    sys.exit(app.exec_()) #Quit nicely
