# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
#from functions.dataLoad import dataLoad
#from functions.dataPlot import dataPlot
#from functions.dataStatistics import dataStatistics
#from functions.userinput import displayMenu,inputStr,header
#from functions.filterData import filterData,printFilter
import sys

class Ui_MainWindow(object):
    def __init__(self):
        object.__init__(self)
        self.setupUi(self)
 #       self.dataload()
        
    
    def setupUi(self, Ui_MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(919, 664)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.welcome_label = QtWidgets.QLabel(self.centralwidget)
        self.welcome_label.setObjectName("welcome_label")
        self.verticalLayout.addWidget(self.welcome_label, 0, QtCore.Qt.AlignHCenter)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.command_frame = QtWidgets.QFrame(self.frame)
        self.command_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.command_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.command_frame.setObjectName("command_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.command_frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.dataload_box = QtWidgets.QGroupBox(self.command_frame)
        self.dataload_box.setObjectName("dataload_box")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.dataload_box)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.dataload_label = QtWidgets.QLabel(self.dataload_box)
        self.dataload_label.setObjectName("dataload_label")
        self.horizontalLayout_2.addWidget(self.dataload_label)
        self.dataload_input = QtWidgets.QLineEdit(self.dataload_box)
        self.dataload_input.setText("")
        self.dataload_input.setObjectName("dataload_input")
        self.horizontalLayout_2.addWidget(self.dataload_input)
        self.dataload_btn = QtWidgets.QPushButton(self.dataload_box)
        self.dataload_btn.setObjectName("dataload_btn")
        self.horizontalLayout_2.addWidget(self.dataload_btn)
        self.verticalLayout_3.addWidget(self.dataload_box)
        self.line_5 = QtWidgets.QFrame(self.command_frame)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_3.addWidget(self.line_5)
        self.command_box = QtWidgets.QGroupBox(self.command_frame)
        self.command_box.setObjectName("command_box")
        self.gridLayout = QtWidgets.QGridLayout(self.command_box)
        self.gridLayout.setObjectName("gridLayout")
        self.stat_btn = QtWidgets.QPushButton(self.command_box)
        self.stat_btn.setObjectName("stat_btn")
        self.gridLayout.addWidget(self.stat_btn, 0, 0, 1, 1)
        self.plot_btn = QtWidgets.QPushButton(self.command_box)
        self.plot_btn.setObjectName("plot_btn")
        self.gridLayout.addWidget(self.plot_btn, 0, 1, 1, 1)
        self.showdata_btn = QtWidgets.QPushButton(self.command_box)
        self.showdata_btn.setObjectName("showdata_btn")
        self.gridLayout.addWidget(self.showdata_btn, 1, 0, 1, 2)
        self.verticalLayout_3.addWidget(self.command_box)
        self.horizontalLayout.addWidget(self.command_frame)
        self.line_3 = QtWidgets.QFrame(self.frame)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout.addWidget(self.line_3)
        self.filterdata_box = QtWidgets.QGroupBox(self.frame)
        self.filterdata_box.setObjectName("filterdata_box")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.filterdata_box)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.bacteria_box = QtWidgets.QGroupBox(self.filterdata_box)
        self.bacteria_box.setObjectName("bacteria_box")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.bacteria_box)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.bac1_chk = QtWidgets.QCheckBox(self.bacteria_box)
        self.bac1_chk.setObjectName("bac1_chk")
        self.verticalLayout_2.addWidget(self.bac1_chk)
        self.bac2_chk = QtWidgets.QCheckBox(self.bacteria_box)
        self.bac2_chk.setObjectName("bac2_chk")
        self.verticalLayout_2.addWidget(self.bac2_chk)
        self.bac3_chk = QtWidgets.QCheckBox(self.bacteria_box)
        self.bac3_chk.setObjectName("bac3_chk")
        self.verticalLayout_2.addWidget(self.bac3_chk)
        self.bac4_chk = QtWidgets.QCheckBox(self.bacteria_box)
        self.bac4_chk.setObjectName("bac4_chk")
        self.verticalLayout_2.addWidget(self.bac4_chk)
        self.horizontalLayout_4.addWidget(self.bacteria_box)
        self.range_box = QtWidgets.QGroupBox(self.filterdata_box)
        self.range_box.setObjectName("range_box")
        self.formLayout = QtWidgets.QFormLayout(self.range_box)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.growth_label = QtWidgets.QLabel(self.range_box)
        self.growth_label.setObjectName("growth_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.growth_label)
        self.growthfrom_label = QtWidgets.QLabel(self.range_box)
        self.growthfrom_label.setObjectName("growthfrom_label")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.growthfrom_label)
        self.growthto_label = QtWidgets.QLabel(self.range_box)
        self.growthto_label.setObjectName("growthto_label")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.growthto_label)
        self.growthfrom_input = QtWidgets.QLineEdit(self.range_box)
        self.growthfrom_input.setObjectName("growthfrom_input")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.growthfrom_input)
        self.growthto_input = QtWidgets.QLineEdit(self.range_box)
        self.growthto_input.setObjectName("growthto_input")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.growthto_input)
        self.growth_btn = QtWidgets.QPushButton(self.range_box)
        self.growth_btn.setObjectName("growth_btn")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.SpanningRole, self.growth_btn)
        self.temp_label = QtWidgets.QLabel(self.range_box)
        self.temp_label.setObjectName("temp_label")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.temp_label)
        self.tempfrom_label = QtWidgets.QLabel(self.range_box)
        self.tempfrom_label.setObjectName("tempfrom_label")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.tempfrom_label)
        self.tempto_label = QtWidgets.QLabel(self.range_box)
        self.tempto_label.setObjectName("tempto_label")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.tempto_label)
        self.tempfrom_input = QtWidgets.QLineEdit(self.range_box)
        self.tempfrom_input.setObjectName("tempfrom_input")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.tempfrom_input)
        self.tempto_input = QtWidgets.QLineEdit(self.range_box)
        self.tempto_input.setObjectName("tempto_input")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.tempto_input)
        self.tempBtn = QtWidgets.QPushButton(self.range_box)
        self.tempBtn.setObjectName("tempBtn")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.SpanningRole, self.tempBtn)
        self.line_4 = QtWidgets.QFrame(self.range_box)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.line_4)
        self.horizontalLayout_4.addWidget(self.range_box)
        self.horizontalLayout.addWidget(self.filterdata_box)
        self.verticalLayout.addWidget(self.frame)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.display_box = QtWidgets.QGroupBox(self.centralwidget)
        self.display_box.setObjectName("display_box")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.display_box)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.columnView = QtWidgets.QColumnView(self.display_box)
        self.columnView.setObjectName("columnView")
        self.horizontalLayout_5.addWidget(self.columnView)
        self.verticalLayout.addWidget(self.display_box)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 919, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Bacteria Data Analysis"))
        self.welcome_label.setText(_translate("MainWindow", "Welcome to the Bacteria Data Analysis program"))
        self.dataload_box.setTitle(_translate("MainWindow", "Dataload"))
        self.dataload_label.setText(_translate("MainWindow", "Enter the name of the datafile:"))
        self.dataload_btn.setText(_translate("MainWindow", "Load Data"))
        self.command_box.setTitle(_translate("MainWindow", "Commands"))
        self.stat_btn.setText(_translate("MainWindow", "Display Statistics"))
        self.plot_btn.setText(_translate("MainWindow", "Generate plots"))
        self.showdata_btn.setText(_translate("MainWindow", "Show data"))
        self.filterdata_box.setTitle(_translate("MainWindow", "Filter Data"))
        self.bacteria_box.setTitle(_translate("MainWindow", "Bacteria"))
        self.bac1_chk.setText(_translate("MainWindow", "Salmonella enterica"))
        self.bac2_chk.setText(_translate("MainWindow", "Bacillus cereus"))
        self.bac3_chk.setText(_translate("MainWindow", "Listeria"))
        self.bac4_chk.setText(_translate("MainWindow", "Brochothrix thermosphacta"))
        self.range_box.setTitle(_translate("MainWindow", "Range"))
        self.growth_label.setText(_translate("MainWindow", "Growth rate"))
        self.growthfrom_label.setText(_translate("MainWindow", "From"))
        self.growthto_label.setText(_translate("MainWindow", "To"))
        self.growth_btn.setText(_translate("MainWindow", "Add Filter"))
        self.temp_label.setText(_translate("MainWindow", "Temperature"))
        self.tempfrom_label.setText(_translate("MainWindow", "From"))
        self.tempto_label.setText(_translate("MainWindow", "To"))
        self.tempBtn.setText(_translate("MainWindow", "Add Filter"))
        self.display_box.setTitle(_translate("MainWindow", "Display Window"))
    
    #Creating a function for clicking the dataload button
    #def dataload(self):
#        filename = self.dataload_input.
#        self.dataload_btn.clicked(filename)


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
